spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_ssm?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5

# 配置MyBatis日志
mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 配置MyBatis-Plus操作表的默认前缀
      #      table-prefix: t_
      # 配置MyBatis-Plus的主键策略
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package:
#    com.yao.yu.entity
#  # 配置扫描通用枚举
#  type-enums-package:
#    com.guigu.mybatisplus.enums
